#ifndef USERMANAGEMENTIF_GLOBAL_H
#define USERMANAGEMENTIF_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USERMANAGEMENTIF_LIBRARY)
#  define USERMANAGEMENTIFSHARED_EXPORT Q_DECL_EXPORT
#else
#  define USERMANAGEMENTIFSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USERMANAGEMENTIF_GLOBAL_H
