#pragma once

#include <QtCore/qglobal.h>

#if defined(USERMANAGEMENTIF_LIBRARY)
#  define USERMANAGEMENTIFSHARED_EXPORT Q_DECL_EXPORT
#else
#  define USERMANAGEMENTIFSHARED_EXPORT Q_DECL_IMPORT
#endif
