#ifndef SELL_INVOICING_GLOBAL_H
#define SELL_INVOICING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SELL_INVOICING_LIBRARY)
#  define SELL_INVOICINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SELL_INVOICINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SELL_INVOICING_GLOBAL_H
