#ifndef CASH_INVOICING_GLOBAL_H
#define CASH_INVOICING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CASH_INVOICING_LIBRARY)
#  define CASH_INVOICINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CASH_INVOICINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CASH_INVOICING_GLOBAL_H
