#ifndef USERMANAGEMENT_INVOICING_GLOBAL_H
#define USERMANAGEMENT_INVOICING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USERMANAGEMENT_INVOICING_LIBRARY)
#  define USERMANAGEMENT_INVOICINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define USERMANAGEMENT_INVOICINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USERMANAGEMENT_INVOICING_GLOBAL_H
