#ifndef PRODUCTMANAGEMENTIF_GLOBAL_H
#define PRODUCTMANAGEMENTIF_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PRODUCTMANAGEMENTIF_LIBRARY)
#  define PRODUCTMANAGEMENTIFSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRODUCTMANAGEMENTIFSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PRODUCTMANAGEMENTIF_GLOBAL_H
