#pragma once

#include <QtCore/qglobal.h>

#if defined(PRODUCTMANAGEMENTIF_LIBRARY)
#  define PRODUCTMANAGEMENTIFSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRODUCTMANAGEMENTIFSHARED_EXPORT Q_DECL_IMPORT
#endif
