#pragma once

#include <QtCore/qglobal.h>

#if defined(PURCHASE_INVOICING_LIBRARY)
#  define PURCHASE_INVOICINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PURCHASE_INVOICINGSHARED_EXPORT Q_DECL_IMPORT
#endif
