#ifndef PURCHASE_INVOICING_GLOBAL_H
#define PURCHASE_INVOICING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PURCHASE_INVOICING_LIBRARY)
#  define PURCHASE_INVOICINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PURCHASE_INVOICINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PURCHASE_INVOICING_GLOBAL_H
