#ifndef UPDATEPRODUCTDIALOG_GLOBAL_H
#define UPDATEPRODUCTDIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UPDATEPRODUCTDIALOG_LIBRARY)
#  define UPDATEPRODUCTDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UPDATEPRODUCTDIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UPDATEPRODUCTDIALOG_GLOBAL_H
