#pragma once

#include <QtCore/qglobal.h>

#if defined(UPDATEPRODUCTDIALOG_LIBRARY)
#  define UPDATEPRODUCTDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UPDATEPRODUCTDIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif
