#ifndef STORAGE_INVOICING_GLOBAL_H
#define STORAGE_INVOICING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STORAGE_INVOICING_LIBRARY)
#  define STORAGE_INVOICINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STORAGE_INVOICINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STORAGE_INVOICING_GLOBAL_H
