#pragma once

#include <QtCore/qglobal.h>

#if defined(STORAGE_INVOICING_LIBRARY)
#  define STORAGE_INVOICINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STORAGE_INVOICINGSHARED_EXPORT Q_DECL_IMPORT
#endif
